<Project>
  <ItemGroup>
    <!-- Web -->
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.6" />
    <!-- EF -->
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.6" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.6" />
    <!-- Cache -->
    <PackageVersion Include="Microsoft.Extensions.Caching.Hybrid" Version="10.5.0" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Postgres" Version="1.2.2" />
    <!-- Common extensions -->
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.6" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.6" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.6" />
    <!-- Core Libraries -->
    <PackageVersion Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageVersion Include="Mailjet.Api" Version="4.0.0" />
    <PackageVersion Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
    <PackageVersion Include="Riok.Mapperly" Version="4.3.1" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.1.7" />
    <!-- Tests -->
    <PackageVersion Include="Alba" Version="8.5.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="Moq" Version="4.20.72" />
    <PackageVersion Include="Testcontainers" Version="4.11.0" />
    <PackageVersion Include="Testcontainers.MsSql" Version="4.11.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>