<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>529b9abc-71c1-46d9-a430-b530cbd5b451</UserSecretsId>
	  
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketingSystem.Application\TicketingSystem.Application.csproj" />
    <ProjectReference Include="..\TicketingSystem.Common\TicketingSystem.Common.csproj" />
    <ProjectReference Include="..\TicketingSystem.DataAccess\TicketingSystem.DataAccess.csproj" />
    <ProjectReference Include="..\TicketingSystem.Domain\TicketingSystem.Domain.csproj" />
    <ProjectReference Include="..\TicketingSystem.Infrastructure\TicketingSystem.Infrastructure.csproj" />
  </ItemGroup>

</Project>
