// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketingSystem.DataAccess;

#nullable disable

namespace TicketingSystem.DataAccess.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    partial class TicketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Ticketing")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CartEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Carts", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CartItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("CartId", "OfferId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("CartItems", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Customers", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("391e388c-57a0-85b8-bf75-019dca57d1f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FirstName = "Test",
                            IsDeleted = false,
                            LastName = "User",
                            UserId = new Guid("391e388c-57a0-85b8-bf75-019dca57d1f5")
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("EventDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Events", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-5555-6666-7777-019dc8d2b0cd"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "An amazing concert featuring top artists.",
                            EventDate = new DateTimeOffset(new DateTime(2026, 7, 1, 20, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Concert A",
                            VenueId = new Guid("162c2be4-42d6-8c0f-badf-019dc8c7bc0e")
                        },
                        new
                        {
                            Id = new Guid("55555555-6666-7777-8888-019dc8d2b0ce"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Description = "A captivating theater performance.",
                            EventDate = new DateTimeOffset(new DateTime(2026, 7, 2, 19, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Name = "Theater B",
                            VenueId = new Guid("162c2be4-42d6-8c0f-badf-019dc8c7bc0e")
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.EventManagerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("EventManagers", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OfferEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeatPriceLevelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SeatStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("SeatPriceLevelId");

                    b.HasIndex("SeatId", "EventId", "SeatPriceLevelId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Offers", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-7777-8888-9999-019dc8d2b0cf"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventId = new Guid("44444444-5555-6666-7777-019dc8d2b0cd"),
                            IsDeleted = false,
                            Price = 100m,
                            SeatId = new Guid("11111111-2222-3333-4444-019dc8d2b0c7"),
                            SeatPriceLevelId = new Guid("aaaaaaaa-bbbb-cccc-dddd-019dc8d2b0ca"),
                            SeatStatus = 0
                        },
                        new
                        {
                            Id = new Guid("77777777-8888-9999-0000-019dc8d2b0d0"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventId = new Guid("44444444-5555-6666-7777-019dc8d2b0cd"),
                            IsDeleted = false,
                            Price = 50m,
                            SeatId = new Guid("22222222-3333-4444-5555-019dc8d2b0c8"),
                            SeatPriceLevelId = new Guid("bbbbbbbb-cccc-dddd-eeee-019dc8d2b0cb"),
                            SeatStatus = 0
                        },
                        new
                        {
                            Id = new Guid("88888888-9999-0000-1111-019dc8d2b0d1"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventId = new Guid("44444444-5555-6666-7777-019dc8d2b0cd"),
                            IsDeleted = false,
                            Price = 200m,
                            SeatId = new Guid("33333333-4444-5555-6666-019dc8d2b0c9"),
                            SeatPriceLevelId = new Guid("cccccccc-dddd-eeee-ffff-019dc8d2b0cc"),
                            SeatStatus = 0
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CartId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.PaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ExternalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SeatEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("SectionRowId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SectionRowId", "SeatNumber")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Seats", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-2222-3333-4444-019dc8d2b0c7"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SeatNumber = 1,
                            SectionRowId = new Guid("d9a7c8e5-9b3e-8f1a-9c83-019dc8d2b0c4"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("22222222-3333-4444-5555-019dc8d2b0c8"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SeatNumber = 2,
                            SectionRowId = new Guid("d9a7c8e5-9b3e-8f1a-9c83-019dc8d2b0c4"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("33333333-4444-5555-6666-019dc8d2b0c9"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SeatNumber = 1,
                            SectionRowId = new Guid("a1b2c3d4-5678-90ab-cdef-019dc8d2b0c5"),
                            Type = 2
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SeatPriceLevelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PriceLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PriceLevel")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SeatPriceLevels", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-bbbb-cccc-dddd-019dc8d2b0ca"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PriceLevel = 1
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-cccc-dddd-eeee-019dc8d2b0cb"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PriceLevel = 2
                        },
                        new
                        {
                            Id = new Guid("cccccccc-dddd-eeee-ffff-019dc8d2b0cc"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            PriceLevel = 3
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("VenueId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Sections", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e9f97b6c-28cf-8a84-ab83-019dc8d2025f"),
                            Code = "Section 1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            VenueId = new Guid("162c2be4-42d6-8c0f-badf-019dc8c7bc0e")
                        },
                        new
                        {
                            Id = new Guid("08c2bc8d-820f-86c2-aa9f-019dc8d2376a"),
                            Code = "Section 2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            VenueId = new Guid("162c2be4-42d6-8c0f-badf-019dc8c7bc0e")
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SectionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SectionId", "Code")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("SectionRows", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d9a7c8e5-9b3e-8f1a-9c83-019dc8d2b0c4"),
                            Code = "Row 1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SectionId = new Guid("e9f97b6c-28cf-8a84-ab83-019dc8d2025f")
                        },
                        new
                        {
                            Id = new Guid("a1b2c3d4-5678-90ab-cdef-019dc8d2b0c5"),
                            Code = "Row 2",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SectionId = new Guid("e9f97b6c-28cf-8a84-ab83-019dc8d2025f")
                        },
                        new
                        {
                            Id = new Guid("12345678-90ab-cdef-1234-019dc8d2b0c6"),
                            Code = "Row 1",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            SectionId = new Guid("08c2bc8d-820f-86c2-aa9f-019dc8d2376a")
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.TicketEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OfferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OfferId")
                        .IsUnique();

                    b.HasIndex("OrderId");

                    b.HasIndex("CustomerId", "OfferId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Tickets", "Ticketing");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("391e388c-57a0-85b8-bf75-019dca57d1f5"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Email = "test.user@ticketing.domain",
                            IsDeleted = false,
                            Type = 1
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.VenueEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Venues", "Ticketing");

                    b.HasData(
                        new
                        {
                            Id = new Guid("162c2be4-42d6-8c0f-badf-019dc8c7bc0e"),
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 10, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            IsDeleted = false,
                            Location = "Address 1",
                            Name = "Venue 1"
                        });
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CartEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.CustomerEntity", null)
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CartItemEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.CartEntity", null)
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.OfferEntity", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("TicketingSystem.DataAccess.Entities.CustomerEntity", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.EventEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.VenueEntity", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.EventManagerEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.UserEntity", "User")
                        .WithOne()
                        .HasForeignKey("TicketingSystem.DataAccess.Entities.EventManagerEntity", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OfferEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.EventEntity", "Event")
                        .WithMany("Offers")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.SeatEntity", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.SeatPriceLevelEntity", "SeatPriceLevel")
                        .WithMany()
                        .HasForeignKey("SeatPriceLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Seat");

                    b.Navigation("SeatPriceLevel");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OrderEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.CartEntity", "Cart")
                        .WithOne()
                        .HasForeignKey("TicketingSystem.DataAccess.Entities.OrderEntity", "CartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.CustomerEntity", null)
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.PaymentEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.OrderEntity", null)
                        .WithMany("Payments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SeatEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.SectionRowEntity", "SectionRow")
                        .WithMany("Seats")
                        .HasForeignKey("SectionRowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("SectionRow");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.VenueEntity", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionRowEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.SectionEntity", "Section")
                        .WithMany("Rows")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Section");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.TicketEntity", b =>
                {
                    b.HasOne("TicketingSystem.DataAccess.Entities.CustomerEntity", null)
                        .WithMany("Tickets")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.OfferEntity", "Offer")
                        .WithOne("Ticket")
                        .HasForeignKey("TicketingSystem.DataAccess.Entities.TicketEntity", "OfferId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TicketingSystem.DataAccess.Entities.OrderEntity", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CartEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.CustomerEntity", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.EventEntity", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OfferEntity", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.OrderEntity", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionEntity", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.SectionRowEntity", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("TicketingSystem.DataAccess.Entities.VenueEntity", b =>
                {
                    b.Navigation("Sections");
                });
#pragma warning restore 612, 618
        }
    }
}
